{% set data = load_setup_py_data() %}

package:
  name: wsp-jacquard
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: auto
  noarch: python

requirements:
  host:
    - python
  run:
    - python
    - six >=1.10

about:
  home: https://github.com/wsp-sag/wsp-jacquard
  license: MIT
  license_file: LICENSE
  summary: JSON-based configuration handler for models.

extra:
  maintainers:
    - Brian Cheung
    - Peter Kucirek
